name: Sync with betterncm database full.

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Sync with betterncm database.
        run: wget -O ./full.json https://betterncm.microblock.cc/api/getFullAnalyzeDataReal
      - name: Commit it back to repo.
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: Sync with betterncm database.
